#   version: '3.3'
services:
  db:
    image: mysql:5.7
#    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./dump/:/var/lib/mysql
    container_name: mysqlPP2
  php-apache:
    build: Dockerfiles/php-apache/
    env_file:
      - .env
    links:
      - db:${MYSQL_SERVER}
    volumes:
      - ./www/:/var/www/html
    ports:
      - ${PHP_PORT}:80
    container_name: AppPP2-25-03
